### ISSUE TITLE
Category list for Kinetics-Sound dataset

### ISSUE THREAD

**Issue by lst627** [pritamqu/CrissCross#4]
Hi, I am planning to do research based on your model. I found that in the paper that you cited (Look, listen and
learn), there are 34 classes in Kinetics-Sound. Among these classes, 32 classes are used in your research. Could you provide the category list? Many thanks for considering my request.

**Comment by pritamqu** [comment]
Hi @lst627, 

Thanks for your interest in our work. Due to the label name change in the later version of Kinetics400; we used 32 classes which are mentioned below.

```


class_names = ["blowing_nose", "blowing_out_candles", "bowling", 
            "chopping_wood", "dribbling_basketball",  "laughing", "mowing_lawn", 
            "playing_accordion", "playing_bagpipes", "playing_bass_guitar", 
            "playing_clarinet", "playing_drums", "playing_guitar", "playing_harmonica",
            "playing_keyboard", "playing_organ", "playing_piano", "playing_saxophone",
            "playing_trombone", "playing_trumpet", "playing_violin", "playing_xylophone",
            "ripping_paper", "shoveling_snow", "shuffling_cards", "singing",
            "stomping_grapes", "strumming_guitar", "tap_dancing", "tapping_guitar",
            "tapping_pen", "tickling"] 

```

**Comment by lst627** [comment]
Thanks for your quick response!
